In [8]:
from models import LinearRegression, BoostingModel, create_nn, MLPModel
from train import ClimateDataset, evaluate, make_train_test
import pandas as pd
import torch
import numpy as np
import itertools
from tqdm.notebook import tqdm

def feature_importance(booster):
    return pd.DataFrame({
        'feature': booster.feature_name(),
        'importance': booster.feature_importance(importance_type='gain')
    }).sort_values('importance', ascending=False).reset_index(drop=True)

FIRST_YEAR = 2007
SPLIT_YEAR = 2016
LAST_YEAR = 2019

def make_ds(element, args):
    return make_train_test(element, FIRST_YEAR, SPLIT_YEAR, LAST_YEAR, args)

In [2]:
ds = ClimateDataset('aice', lead_times=[3], periods=[3])
model = BoostingModel(variables=ds.variables.copy())
model.fit(ds)
feature_importance(model.model)

       feature     importance
0         aice  243846.577600
1      cos_lat   16729.302294
2           ps    8547.605698
3         t850    7712.167528
4      sin_lon    7097.492949
5          olr    6993.244529
6         h500    6824.411523
7         hice    6786.388554
8         v850    6028.637073
9          sst    5990.564500
10     cos_lon    3785.110461
11       t2max    3441.390424
12        u850    3130.765502
13        uv10    2735.834682
14         rq2    2599.944957
15       t2min    1910.994256
16          t2    1437.713337
17         cld    1179.115872
18        prec    1131.609003
19  sin_period       0.000000
20  cos_period       0.000000

In [3]:
ds = ClimateDataset('swe', lead_times=[3], periods=list(range(44, 49)))
model = BoostingModel(variables=ds.variables.copy())
model.fit(ds)
feature_importance(model.model)

       feature   importance
0        t2min  540728356.0
1          swe  345903520.0
2      cos_lat  290962796.0
3      cos_lon  237870206.0
4      sin_lon  221507471.0
5          tvl  218294927.0
6         sdor  189033583.0
7         h500  168372332.0
8           t2  158488576.0
9           ww  147749781.0
10        v850  132091792.0
11          ps  103620215.0
12        u850  102618582.0
13           z   87582560.0
14         olr   85790871.0
15        t850   78501741.0
16         cld   64410021.0
17        prec   58880406.0
18          ws   57867869.0
19       t2max   55318679.0
20         cvl   51401595.0
21        uv10   50330413.0
22  sin_period   49463002.0
23         lsm   37055644.0
24         slt   36109084.0
25         rq2   23785139.0
26         cvh   20626886.0
27  cos_period   15826003.0
28          cl    7222562.0
29         tvh    2896815.0

In [2]:
def score_model(model, X, y, lat, climate, s, mx=1):
    model.__fit__(X[:, s], y)
    y_pred = torch.clamp(model.predict(X[:, s]) + climate, 0, max=mx)
    return loss_rmse(y_pred, y + climate, lat)

def shapley_approximation(model, variables, X, y, lat, climate, mx=1, n_samples=500):
    n = X.shape[1]
    shapley_values = np.zeros(n)
    
    for _ in tqdm(range(n_samples)):
        order = np.random.permutation(n)
        cur_set = []
        prev_score = score_model(model, X, y, lat, climate, cur_set, mx=mx)
        for i, idx in enumerate(order):
            cur_set.append(idx)
            cur_score = score_model(model, X, y, lat, climate, cur_set, mx=mx)
            for idx in cur_set:
                shapley_values[idx] += (cur_score - prev_score) / (i + 1)
            prev_score = cur_score
    shapley_values /= n_samples / 1000

    return pd.DataFrame({
        'variable': variables,
        'SHAP': -shapley_values
    }).sort_values('SHAP', ascending=False).reset_index(drop=True)

In [3]:
ds = ClimateDataset('aice', lead_times=[3], periods=[3], normed=True, use_cache=True)
ds.set_variables([v for v in ds.variables if v not in ['cos_period', 'sin_period']])
X, y, lat, climate = ds.load_all()
shapley_approximation(LinearRegression([]), ds.variables.copy(), X, y, lat, climate, n_samples=1000)

  0%|          | 0/1000 [00:00<?, ?it/s]

   variable      SHAP
0      aice  5.786736
1   cos_lat  3.000968
2        ps  1.675598
3       sst  1.665752
4     t2min  1.640753
5       olr  1.636141
6      t850  1.621056
7      uv10  1.587313
8     t2max  1.576886
9      prec  1.547284
10       t2  1.531745
11     v850  1.529202
12     hice  1.523626
13     u850  1.522739
14     h500  1.521812
15      rq2  1.510334
16  sin_lon  1.505852
17  cos_lon  1.500664
18      cld  1.462086

In [6]:
full_variables = ['hice', 'sst', 'aice', 'cld', 'h500', 'olr', 'prec', 'ps', 'rq2', 't2', 't2max', 't2min', 't850',
                  'u850', 'uv10', 'v850', 'cos_lat', 'sin_lon', 'cos_lon', 'sin_period', 'cos_period']
dsTrain, dsTest = make_ds('aice', args={"lead_times": [3], "periods": [3], "normed": True, "cache_level": 2, "batch_size": 1e8,
                                        "variables": full_variables})
model = create_nn('aice', MLPModel,
            {'input_size': len(dsTrain.variables), 'hidden_layers': [16, 8] },
            test=dsTest, lr=0.003, epochs=170, verbose=False)
#trainLoss, testLoss = model.fit(dsTrain)
testLoss[-1]

([-0.45431843400001526,
  -0.4350205361843109,
  -0.41617515683174133,
  -0.3975442051887512,
  -0.37892934679985046,
  -0.36052724719047546,
  -0.3425058126449585,
  -0.3250606656074524,
  -0.3081733286380768,
  -0.2916460335254669,
  -0.27522698044776917,
  -0.2587161958217621,
  -0.24195346236228943,
  -0.2249734103679657,
  -0.20791257917881012,
  -0.1907934546470642,
  -0.1736024022102356,
  -0.15639682114124298,
  -0.13920176029205322,
  -0.12198332697153091,
  -0.10464233160018921,
  -0.0870252475142479,
  -0.06889922171831131,
  -0.04995371773838997,
  -0.029764924198389053,
  -0.007742252200841904,
  0.01692875660955906,
  0.04542296752333641,
  0.07928164303302765,
  0.12064426392316818,
  0.17218369245529175,
  0.23657715320587158,
  0.31504103541374207,
  0.4041192829608917,
  0.49140337109565735,
  0.5590240359306335,
  0.5963003635406494,
  0.6096937656402588,
  0.6121944189071655,
  0.6123194694519043,
  0.6134182214736938,
  0.6167835593223572,
  0.6225248575210571,
  0.6300429701805115,
  0.6390191912651062,
  0.6490154266357422,
  0.659635066986084,
  0.670209527015686,
  0.6800529360771179,
  0.6884626746177673,
  0.6947199702262878,
  0.6987317800521851,
  0.7014719247817993,
  0.7044501304626465,
  0.7088340520858765,
  0.7150081396102905,
  0.7226710319519043,
  0.7311016917228699,
  0.7394687533378601,
  0.7471065521240234,
  0.7536615133285522,
  0.7590957283973694,
  0.7636012434959412,
  0.7674800753593445,
  0.7710177302360535,
  0.7744064331054688,
  0.7776947617530823,
  0.7808218002319336,
  0.7836437821388245,
  0.7859951257705688,
  0.7877780199050903,
  0.7890204787254333,
  0.7898942232131958,
  0.7906647324562073,
  0.7916058897972107,
  0.7928732633590698,
  0.7944649457931519,
  0.7962406277656555,
  0.7980030179023743,
  0.7995776534080505,
  0.800866961479187,
  0.8018564581871033,
  0.8025931119918823,
  0.8031548857688904,
  0.8036250472068787,
  0.8040717244148254,
  0.8045417666435242,
  0.8050552010536194,
  0.8056063055992126,
  0.8061721324920654,
  0.8067285418510437,
  0.8072546720504761,
  0.807736337184906,
  0.8081710338592529,
  0.8085742592811584,
  0.8089635968208313,
  0.8093546032905579,
  0.8097578883171082,
  0.8101708292961121,
  0.8105804324150085,
  0.8109713792800903,
  0.8113349676132202,
  0.8116669058799744,
  0.8119714856147766,
  0.8122581243515015,
  0.8125399947166443,
  0.8128297328948975,
  0.8131334781646729,
  0.8134446144104004,
  0.8137478828430176,
  0.8140239715576172,
  0.8142634630203247,
  0.8144710659980774,
  0.8146624565124512,
  0.8148548603057861,
  0.815054714679718,
  0.8152564167976379,
  0.8154495358467102,
  0.8156284689903259,
  0.8157947659492493,
  0.8159535527229309,
  0.816107451915741,
  0.8162546753883362,
  0.8163926005363464,
  0.816522479057312,
  0.8166473507881165,
  0.8167713284492493,
  0.8168975710868835,
  0.8170258402824402,
  0.8171530961990356,
  0.8172762393951416,
  0.81739342212677,
  0.8175061345100403,
  0.8176180124282837,
  0.8177309036254883,
  0.8178437352180481,
  0.817955493927002,
  0.8180660009384155,
  0.8181771039962769,
  0.8182897567749023,
  0.8184036016464233,
  0.8185162544250488,
  0.8186269998550415,
  0.8187360763549805,
  0.8188449740409851,
  0.8189539313316345,
  0.8190627694129944,
  0.8191710710525513,
  0.8192790150642395,
  0.8193871378898621,
  0.8194953203201294,
  0.8196029663085938,
  0.8197097778320312,
  0.819815456867218,
  0.8199204802513123,
  0.8200255036354065,
  0.8201301097869873,
  0.8202349543571472,
  0.8203396797180176,
  0.8204448223114014,
  0.8205500841140747,
  0.8206555843353271,
  0.8207609057426453,
  0.8208661079406738,
  0.8209715485572815,
  0.8210772275924683,
  0.8211830258369446,
  0.8212888836860657,
  0.8213949799537659,
  0.8215014338493347],
 [-0.5152173042297363,
  -0.49935588240623474,
  -0.4839663803577423,
  -0.46849748492240906,
  -0.4524146616458893,
  -0.4359871447086334,
  -0.41996434330940247,
  -0.40462401509284973,
  -0.3892114460468292,
  -0.3731768727302551,
  -0.3564770519733429,
  -0.3388764560222626,
  -0.319990336894989,
  -0.299701064825058,
  -0.27803701162338257,
  -0.25501197576522827,
  -0.23045267164707184,
  -0.20401941239833832,
  -0.17531690001487732,
  -0.1439446210861206,
  -0.10940264910459518,
  -0.07129892706871033,
  -0.02920975536108017,
  0.017312530428171158,
  0.06893595308065414,
  0.12659186124801636,
  0.19129303097724915,
  0.26413261890411377,
  0.34480953216552734,
  0.4298883080482483,
  0.5121940970420837,
  0.5832381844520569,
  0.6365828514099121,
  0.6706907749176025,
  0.6889991164207458,
  0.6967508792877197,
  0.6987795233726501,
  0.6984539031982422,
  0.6979367733001709,
  0.6980234980583191,
  0.6987552642822266,
  0.700043261051178,
  0.7018090486526489,
  0.7039671540260315,
  0.7064233422279358,
  0.7090811729431152,
  0.7117844223976135,
  0.7144327163696289,
  0.7170187830924988,
  0.7195848822593689,
  0.7223140001296997,
  0.7254760265350342,
  0.7293319702148438,
  0.7339972853660583,
  0.7394216656684875,
  0.7454456090927124,
  0.7518329620361328,
  0.758309543132782,
  0.7646500468254089,
  0.7706912755966187,
  0.7763317823410034,
  0.781518816947937,
  0.7862904667854309,
  0.7906876802444458,
  0.7947317957878113,
  0.7984360456466675,
  0.8018021583557129,
  0.804777979850769,
  0.8072183132171631,
  0.8090681433677673,
  0.8103943467140198,
  0.8113745450973511,
  0.8122615814208984,
  0.8133267760276794,
  0.8147486448287964,
  0.8165642619132996,
  0.8186700344085693,
  0.8208855390548706,
  0.8230211734771729,
  0.8249262571334839,
  0.826532244682312,
  0.8278217315673828,
  0.8288206458091736,
  0.8295875191688538,
  0.8301945328712463,
  0.8307105302810669,
  0.8311964869499207,
  0.8316912055015564,
  0.8322134613990784,
  0.8327654004096985,
  0.833332896232605,
  0.8338985443115234,
  0.8344303369522095,
  0.8349041938781738,
  0.8353065252304077,
  0.8356370329856873,
  0.8358913660049438,
  0.836060643196106,
  0.8361386656761169,
  0.8361210227012634,
  0.8360077142715454,
  0.8358055353164673,
  0.8355275392532349,
  0.8351984620094299,
  0.834847092628479,
  0.8344974517822266,
  0.8341661691665649,
  0.8338559865951538,
  0.8335602879524231,
  0.8332663178443909,
  0.8329574465751648,
  0.8326354622840881,
  0.8323150873184204,
  0.8320202827453613,
  0.8317617774009705,
  0.8315361142158508,
  0.8313360214233398,
  0.8311593532562256,
  0.831007182598114,
  0.8308817148208618,
  0.83078533411026,
  0.8307160139083862,
  0.8306654691696167,
  0.8306275010108948,
  0.8305980563163757,
  0.8305723667144775,
  0.8305493593215942,
  0.8305323123931885,
  0.8305246829986572,
  0.8305302858352661,
  0.8305504322052002,
  0.8305840492248535,
  0.8306335806846619,
  0.8306955695152283,
  0.830763041973114,
  0.8308286666870117,
  0.8308863043785095,
  0.8309305906295776,
  0.8309590816497803,
  0.8309707641601562,
  0.8309673070907593,
  0.8309531211853027,
  0.8309354186058044,
  0.8309201002120972,
  0.8309130072593689,
  0.830917239189148,
  0.830934464931488,
  0.8309664726257324,
  0.8310140371322632,
  0.8310758471488953,
  0.8311491012573242,
  0.8312293887138367,
  0.831311821937561,
  0.8313924074172974,
  0.8314676284790039,
  0.8315358757972717,
  0.8315958380699158,
  0.831648588180542,
  0.8316965103149414,
  0.8317425847053528,
  0.8317879438400269,
  0.8318321704864502,
  0.8318758010864258,
  0.8319187760353088,
  0.8319600224494934,
  0.8319999575614929,
  0.8320375680923462,
  0.8320714235305786,
  0.832099199295044,
  0.8321186304092407])

In [9]:
def get_loss(variant, X, y, lat, X_test, y_test, lat_test, variables, idxs):
    model = None
    if variant == 'aice':
        model = create_nn('aice', MLPModel,
            {'input_size': len(variables), 'hidden_layers': [4, 2] }, lr=0.04, epochs=200, verbose=False)
    elif variant == 'swe':
        model = create_nn('swe', MLPModel,
            {'input_size': len(variables), 'hidden_layers': [4, 4] }, lr=0.01, epochs=60, verbose=False)

    trainLosses, testLosses = model.fit_simple(X[:, idxs], y, lat, X_test[:, idxs], y_test, lat_test)
    return np.max(testLosses)

def feature_selection(variant, variables):
    history = []
    current_vars = variables.copy()
    current_idxs = list(range(len(variables)))

    dsTrain, dsTest = make_ds('aice', args={
        "lead_times": [3], "periods": [3], "normed": True, "batch_size": 1e8, "variables": variables, 'cache_level': 0
    }) if variant == 'aice' else make_ds('swe', args={
        "lead_times": [3], "periods": [44, 45, 46, 47], "normed": True, "batch_size": 1e8, "variables": variables, 'cache_level': 0
    })
    X, y, lat = dsTrain.load_all()
    X_test, y_test, lat_test = dsTest.load_all()

    current_loss = get_loss(variant, X, y, lat, X_test, y_test, lat_test, current_vars, current_idxs)
    print(np.round(current_loss, 3), current_vars)
    history.append({'variables': ';'.join(current_vars), 'loss': current_loss})

    while len(current_vars) > 1:
        best_vars = None
        best_idxs = None
        best_loss = 0
        
        for i_remove, v_remove in zip(current_idxs, current_vars):
            candidate_vars = [v for v in current_vars if v != v_remove]
            candidate_idxs = [i for i in current_idxs if i != i_remove]
            candidate_loss = get_loss(variant, X, y, lat, X_test, y_test, lat_test, candidate_vars, candidate_idxs)

            if candidate_loss > best_loss:
                best_loss = candidate_loss
                best_vars = candidate_vars
                best_idxs = candidate_idxs

        current_vars = best_vars
        current_idxs = best_idxs
        current_loss = best_loss
        print(np.round(current_loss, 3), current_vars)
        history.append({'variables': ';'.join(current_vars), 'loss': current_loss})
        pd.DataFrame(history).to_csv(f'009_{variant}.csv', index=False)
 
    df = pd.DataFrame(history)
    df.to_csv(f'009_{variant}.csv', index=False)
    return df

In [3]:
ice_variables = ['hice', 'sst', 'aice', 'cld', 'h500', 'olr', 'prec', 'ps', 'rq2', 't2', 't2max', 't2min', 't850',
                  'u850', 'uv10', 'v850', 'cos_lat', 'sin_lon', 'cos_lon', 'sin_period', 'cos_period']
feature_selection('aice', ice_variables)

0.846 ['hice', 'sst', 'aice', 'cld', 'h500', 'olr', 'prec', 'ps', 'rq2', 't2', 't2max', 't2min', 't850', 'u850', 'uv10', 'v850', 'cos_lat', 'sin_lon', 'cos_lon', 'sin_period', 'cos_period']
0.847 ['hice', 'sst', 'aice', 'cld', 'h500', 'olr', 'prec', 'ps', 'rq2', 't2', 't2max', 't2min', 't850', 'u850', 'uv10', 'cos_lat', 'sin_lon', 'cos_lon', 'sin_period', 'cos_period']
0.857 ['hice', 'sst', 'aice', 'cld', 'h500', 'prec', 'ps', 'rq2', 't2', 't2max', 't2min', 't850', 'u850', 'uv10', 'cos_lat', 'sin_lon', 'cos_lon', 'sin_period', 'cos_period']
0.856 ['hice', 'sst', 'aice', 'cld', 'h500', 'prec', 'ps', 'rq2', 't2', 't2max', 't2min', 't850', 'u850', 'cos_lat', 'sin_lon', 'cos_lon', 'sin_period', 'cos_period']
0.858 ['hice', 'sst', 'aice', 'cld', 'h500', 'prec', 'rq2', 't2', 't2max', 't2min', 't850', 'u850', 'cos_lat', 'sin_lon', 'cos_lon', 'sin_period', 'cos_period']
0.86 ['hice', 'sst', 'aice', 'cld', 'h500', 'rq2', 't2', 't2max', 't2min', 't850', 'u850', 'cos_lat', 'sin_lon', 'cos_lon', 'sin_period', 'cos_period']
0.862 ['hice', 'sst', 'aice', 'cld', 'h500', 'rq2', 't2', 't2max', 't2min', 't850', 'u850', 'sin_lon', 'cos_lon', 'sin_period', 'cos_period']
0.841 ['hice', 'sst', 'aice', 'cld', 'h500', 'rq2', 't2', 't2max', 't2min', 't850', 'u850', 'sin_lon', 'cos_lon', 'cos_period']
0.86 ['hice', 'sst', 'aice', 'cld', 'rq2', 't2', 't2max', 't2min', 't850', 'u850', 'sin_lon', 'cos_lon', 'cos_period']
0.861 ['hice', 'sst', 'aice', 'cld', 'rq2', 't2max', 't2min', 't850', 'u850', 'sin_lon', 'cos_lon', 'cos_period']
0.862 ['sst', 'aice', 'cld', 'rq2', 't2max', 't2min', 't850', 'u850', 'sin_lon', 'cos_lon', 'cos_period']
0.86 ['sst', 'aice', 'cld', 'rq2', 't2max', 't2min', 't850', 'u850', 'sin_lon', 'cos_period']
0.861 ['sst', 'aice', 'cld', 'rq2', 't2max', 't2min', 't850', 'u850', 'sin_lon']
0.86 ['sst', 'aice', 'cld', 't2max', 't2min', 't850', 'u850', 'sin_lon']
0.844 ['sst', 'aice', 't2max', 't2min', 't850', 'u850', 'sin_lon']
0.859 ['sst', 'aice', 't2max', 't850', 'u850', 'sin_lon']
0.863 ['sst', 'aice', 't2max', 't850', 'sin_lon']
0.86 ['sst', 'aice', 't2max', 'sin_lon']
0.857 ['sst', 'aice', 't2max']
0.854 ['sst', 'aice']
0.851 ['aice']

                                            variables      loss
0   hice;sst;aice;cld;h500;olr;prec;ps;rq2;t2;t2ma...  0.845847
1   hice;sst;aice;cld;h500;olr;prec;ps;rq2;t2;t2ma...  0.847190
2   hice;sst;aice;cld;h500;prec;ps;rq2;t2;t2max;t2...  0.857071
3   hice;sst;aice;cld;h500;prec;ps;rq2;t2;t2max;t2...  0.855898
4   hice;sst;aice;cld;h500;prec;rq2;t2;t2max;t2min...  0.858000
5   hice;sst;aice;cld;h500;rq2;t2;t2max;t2min;t850...  0.860014
6   hice;sst;aice;cld;h500;rq2;t2;t2max;t2min;t850...  0.861694
7   hice;sst;aice;cld;h500;rq2;t2;t2max;t2min;t850...  0.841468
8   hice;sst;aice;cld;rq2;t2;t2max;t2min;t850;u850...  0.860240
9   hice;sst;aice;cld;rq2;t2max;t2min;t850;u850;si...  0.860663
10  sst;aice;cld;rq2;t2max;t2min;t850;u850;sin_lon...  0.862076
11  sst;aice;cld;rq2;t2max;t2min;t850;u850;sin_lon...  0.859891
12     sst;aice;cld;rq2;t2max;t2min;t850;u850;sin_lon  0.861196
13         sst;aice;cld;t2max;t2min;t850;u850;sin_lon  0.860102
14             sst;aice;t2max;t2min;t850;u850;sin_lon  0.843887
15                   sst;aice;t2max;t850;u850;sin_lon  0.859270
16                        sst;aice;t2max;t850;sin_lon  0.863061
17                             sst;aice;t2max;sin_lon  0.860103
18                                     sst;aice;t2max  0.857176
19                                           sst;aice  0.854216
20                                               aice  0.850645

In [10]:
swe_variables = ['swe', 'cld', 'h500', 'olr', 'prec', 'ps', 'rq2', 't2', 't2max', 't2min', 't850', 'u850', 'uv10', 'v850', 'ws', 'ww',
            'z', 'sdor', 'cos_lat', 'sin_lon', 'cos_lon']
feature_selection('swe', swe_variables)

0.242 ['swe', 'cld', 'h500', 'olr', 'prec', 'ps', 'rq2', 't2', 't2max', 't2min', 't850', 'u850', 'uv10', 'v850', 'ws', 'ww', 'z', 'sdor', 'cos_lat', 'sin_lon', 'cos_lon']
0.286 ['swe', 'cld', 'h500', 'olr', 'prec', 'ps', 'rq2', 't2', 't2max', 't2min', 't850', 'u850', 'uv10', 'v850', 'ww', 'z', 'sdor', 'cos_lat', 'sin_lon', 'cos_lon']
0.29 ['swe', 'cld', 'olr', 'prec', 'ps', 'rq2', 't2', 't2max', 't2min', 't850', 'u850', 'uv10', 'v850', 'ww', 'z', 'sdor', 'cos_lat', 'sin_lon', 'cos_lon']
0.291 ['swe', 'cld', 'olr', 'prec', 'ps', 'rq2', 't2', 't2max', 't2min', 't850', 'u850', 'uv10', 'ww', 'z', 'sdor', 'cos_lat', 'sin_lon', 'cos_lon']
0.234 ['swe', 'olr', 'prec', 'ps', 'rq2', 't2', 't2max', 't2min', 't850', 'u850', 'uv10', 'ww', 'z', 'sdor', 'cos_lat', 'sin_lon', 'cos_lon']
0.228 ['swe', 'olr', 'prec', 'ps', 'rq2', 't2', 't2max', 't2min', 't850', 'u850', 'uv10', 'ww', 'sdor', 'cos_lat', 'sin_lon', 'cos_lon']
0.291 ['swe', 'olr', 'prec', 'ps', 'rq2', 't2', 't2max', 't2min', 't850', 'u850', 'uv10', 'sdor', 'cos_lat', 'sin_lon', 'cos_lon']
0.208 ['olr', 'prec', 'ps', 'rq2', 't2', 't2max', 't2min', 't850', 'u850', 'uv10', 'sdor', 'cos_lat', 'sin_lon', 'cos_lon']

KeyboardInterrupt:

In [9]:
variables = ['swe', 'cld', 'olr', 'prec', 'ps', 'rq2', 't2', 't2max', 't2min', 't850', 'u850', 'uv10', 'ww', 'z',
             'sdor', 'cos_lat', 'sin_lon', 'cos_lon']
dsTrain, dsTest = make_ds('swe', args={
        "lead_times": [3], "periods": [44, 45, 46, 47, 48], "normed": True, "batch_size": 1e8, "variables": variables, 'cache_level': 2
    })
model = create_nn('swe', MLPModel, {'input_size': len(variables), 'hidden_layers': [4, 4] }, lr=0.05, epochs=500, verbose=True, test=dsTest)
model.fit(dsTrain)

Epoch   1, train loss:   9.5115, test loss:   0.1720, time: 8.02s
Epoch   2, train loss:   9.4800, test loss:   0.1743, time: 0.09s
Epoch   3, train loss:   9.4478, test loss:   0.1746, time: 0.09s
Epoch   4, train loss:   9.4085, test loss:   0.1742, time: 0.09s
Epoch   5, train loss:   9.3600, test loss:   0.1737, time: 0.09s
Epoch   6, train loss:   9.3027, test loss:   0.1728, time: 0.08s
Epoch   7, train loss:   9.2388, test loss:   0.1716, time: 0.09s
Epoch   8, train loss:   9.1765, test loss:   0.1712, time: 0.09s
Epoch   9, train loss:   9.1343, test loss:   0.1725, time: 0.08s
Epoch  10, train loss:   9.1293, test loss:   0.1754, time: 0.09s
Epoch  11, train loss:   9.1340, test loss:   0.1787, time: 0.09s
Epoch  12, train loss:   9.1170, test loss:   0.1825, time: 0.08s
Epoch  13, train loss:   9.0816, test loss:   0.1866, time: 0.09s
Epoch  14, train loss:   9.0414, test loss:   0.1909, time: 0.09s
Epoch  15, train loss:   9.0071, test loss:   0.1948, time: 0.08s
Epoch  16, train loss:   8.9827, test loss:   0.1983, time: 0.09s
Epoch  17, train loss:   8.9630, test loss:   0.2013, time: 0.09s
Epoch  18, train loss:   8.9446, test loss:   0.2040, time: 0.08s
Epoch  19, train loss:   8.9260, test loss:   0.2062, time: 0.09s
Epoch  20, train loss:   8.9068, test loss:   0.2081, time: 0.09s
Epoch  21, train loss:   8.8877, test loss:   0.2102, time: 0.08s
Epoch  22, train loss:   8.8700, test loss:   0.2126, time: 0.09s
Epoch  23, train loss:   8.8554, test loss:   0.2153, time: 0.09s
Epoch  24, train loss:   8.8439, test loss:   0.2181, time: 0.09s
Epoch  25, train loss:   8.8337, test loss:   0.2209, time: 0.09s
Epoch  26, train loss:   8.8228, test loss:   0.2238, time: 0.09s
Epoch  27, train loss:   8.8097, test loss:   0.2270, time: 0.09s
Epoch  28, train loss:   8.7946, test loss:   0.2303, time: 0.09s
Epoch  29, train loss:   8.7790, test loss:   0.2336, time: 0.09s
Epoch  30, train loss:   8.7646, test loss:   0.2367, time: 0.08s
Epoch  31, train loss:   8.7524, test loss:   0.2393, time: 0.09s
Epoch  32, train loss:   8.7432, test loss:   0.2413, time: 0.09s
Epoch  33, train loss:   8.7364, test loss:   0.2431, time: 0.09s
Epoch  34, train loss:   8.7308, test loss:   0.2448, time: 0.09s
Epoch  35, train loss:   8.7251, test loss:   0.2464, time: 0.09s
Epoch  36, train loss:   8.7187, test loss:   0.2480, time: 0.09s
Epoch  37, train loss:   8.7124, test loss:   0.2495, time: 0.09s
Epoch  38, train loss:   8.7072, test loss:   0.2508, time: 0.09s
Epoch  39, train loss:   8.7036, test loss:   0.2521, time: 0.08s
Epoch  40, train loss:   8.7012, test loss:   0.2536, time: 0.09s
Epoch  41, train loss:   8.6988, test loss:   0.2553, time: 0.08s
Epoch  42, train loss:   8.6957, test loss:   0.2571, time: 0.08s
Epoch  43, train loss:   8.6922, test loss:   0.2588, time: 0.09s
Epoch  44, train loss:   8.6886, test loss:   0.2605, time: 0.08s
Epoch  45, train loss:   8.6850, test loss:   0.2619, time: 0.09s
Epoch  46, train loss:   8.6813, test loss:   0.2630, time: 0.09s
Epoch  47, train loss:   8.6773, test loss:   0.2637, time: 0.09s
Epoch  48, train loss:   8.6729, test loss:   0.2641, time: 0.09s
Epoch  49, train loss:   8.6685, test loss:   0.2644, time: 0.09s
Epoch  50, train loss:   8.6642, test loss:   0.2647, time: 0.09s
Epoch  51, train loss:   8.6600, test loss:   0.2650, time: 0.08s
Epoch  52, train loss:   8.6557, test loss:   0.2655, time: 0.09s
Epoch  53, train loss:   8.6510, test loss:   0.2662, time: 0.08s
Epoch  54, train loss:   8.6463, test loss:   0.2670, time: 0.08s
Epoch  55, train loss:   8.6416, test loss:   0.2680, time: 0.09s
Epoch  56, train loss:   8.6371, test loss:   0.2691, time: 0.09s
Epoch  57, train loss:   8.6325, test loss:   0.2704, time: 0.09s
Epoch  58, train loss:   8.6278, test loss:   0.2717, time: 0.09s
Epoch  59, train loss:   8.6230, test loss:   0.2728, time: 0.09s
Epoch  60, train loss:   8.6183, test loss:   0.2738, time: 0.08s
Epoch  61, train loss:   8.6139, test loss:   0.2748, time: 0.09s
Epoch  62, train loss:   8.6098, test loss:   0.2757, time: 0.09s
Epoch  63, train loss:   8.6060, test loss:   0.2767, time: 0.08s
Epoch  64, train loss:   8.6021, test loss:   0.2776, time: 0.09s
Epoch  65, train loss:   8.5984, test loss:   0.2785, time: 0.09s
Epoch  66, train loss:   8.5947, test loss:   0.2792, time: 0.08s
Epoch  67, train loss:   8.5910, test loss:   0.2798, time: 0.09s
Epoch  68, train loss:   8.5876, test loss:   0.2803, time: 0.08s
Epoch  69, train loss:   8.5844, test loss:   0.2805, time: 0.08s
Epoch  70, train loss:   8.5812, test loss:   0.2806, time: 0.09s
Epoch  71, train loss:   8.5778, test loss:   0.2806, time: 0.09s
Epoch  72, train loss:   8.5747, test loss:   0.2805, time: 0.09s
Epoch  73, train loss:   8.5720, test loss:   0.2807, time: 0.09s
Epoch  74, train loss:   8.5692, test loss:   0.2809, time: 0.08s
Epoch  75, train loss:   8.5664, test loss:   0.2811, time: 0.08s
Epoch  76, train loss:   8.5638, test loss:   0.2814, time: 0.09s
Epoch  77, train loss:   8.5612, test loss:   0.2818, time: 0.09s
Epoch  78, train loss:   8.5587, test loss:   0.2820, time: 0.09s
Epoch  79, train loss:   8.5563, test loss:   0.2821, time: 0.09s
Epoch  80, train loss:   8.5540, test loss:   0.2824, time: 0.08s
Epoch  81, train loss:   8.5516, test loss:   0.2827, time: 0.08s
Epoch  82, train loss:   8.5495, test loss:   0.2829, time: 0.09s
Epoch  83, train loss:   8.5473, test loss:   0.2830, time: 0.09s
Epoch  84, train loss:   8.5452, test loss:   0.2830, time: 0.09s
Epoch  85, train loss:   8.5433, test loss:   0.2830, time: 0.09s
Epoch  86, train loss:   8.5414, test loss:   0.2828, time: 0.08s
Epoch  87, train loss:   8.5396, test loss:   0.2825, time: 0.08s
Epoch  88, train loss:   8.5379, test loss:   0.2821, time: 0.09s
Epoch  89, train loss:   8.5363, test loss:   0.2816, time: 0.09s
Epoch  90, train loss:   8.5349, test loss:   0.2813, time: 0.09s
Epoch  91, train loss:   8.5335, test loss:   0.2810, time: 0.09s
Epoch  92, train loss:   8.5322, test loss:   0.2807, time: 0.09s
Epoch  93, train loss:   8.5311, test loss:   0.2805, time: 0.09s
Epoch  94, train loss:   8.5300, test loss:   0.2803, time: 0.09s
Epoch  95, train loss:   8.5289, test loss:   0.2802, time: 0.09s
Epoch  96, train loss:   8.5279, test loss:   0.2800, time: 0.08s
Epoch  97, train loss:   8.5269, test loss:   0.2799, time: 0.09s
Epoch  98, train loss:   8.5260, test loss:   0.2797, time: 0.09s
Epoch  99, train loss:   8.5250, test loss:   0.2797, time: 0.09s
Epoch 100, train loss:   8.5241, test loss:   0.2796, time: 0.09s
Epoch 101, train loss:   8.5233, test loss:   0.2795, time: 0.09s
Epoch 102, train loss:   8.5225, test loss:   0.2794, time: 0.08s
Epoch 103, train loss:   8.5218, test loss:   0.2793, time: 0.09s
Epoch 104, train loss:   8.5211, test loss:   0.2792, time: 0.09s
Epoch 105, train loss:   8.5205, test loss:   0.2791, time: 0.09s
Epoch 106, train loss:   8.5199, test loss:   0.2791, time: 0.09s
Epoch 107, train loss:   8.5194, test loss:   0.2791, time: 0.08s
Epoch 108, train loss:   8.5188, test loss:   0.2792, time: 0.08s
Epoch 109, train loss:   8.5183, test loss:   0.2795, time: 0.09s
Epoch 110, train loss:   8.5178, test loss:   0.2798, time: 0.09s
Epoch 111, train loss:   8.5173, test loss:   0.2801, time: 0.09s
Epoch 112, train loss:   8.5168, test loss:   0.2804, time: 0.09s
Epoch 113, train loss:   8.5163, test loss:   0.2807, time: 0.09s
Epoch 114, train loss:   8.5158, test loss:   0.2809, time: 0.09s
Epoch 115, train loss:   8.5154, test loss:   0.2811, time: 0.09s
Epoch 116, train loss:   8.5150, test loss:   0.2812, time: 0.08s
Epoch 117, train loss:   8.5145, test loss:   0.2813, time: 0.09s
Epoch 118, train loss:   8.5141, test loss:   0.2813, time: 0.09s
Epoch 119, train loss:   8.5137, test loss:   0.2812, time: 0.09s
Epoch 120, train loss:   8.5134, test loss:   0.2811, time: 0.09s
Epoch 121, train loss:   8.5130, test loss:   0.2811, time: 0.09s
Epoch 122, train loss:   8.5126, test loss:   0.2812, time: 0.09s
Epoch 123, train loss:   8.5123, test loss:   0.2813, time: 0.09s
Epoch 124, train loss:   8.5119, test loss:   0.2814, time: 0.09s
Epoch 125, train loss:   8.5116, test loss:   0.2816, time: 0.08s
Epoch 126, train loss:   8.5113, test loss:   0.2818, time: 0.09s
Epoch 127, train loss:   8.5110, test loss:   0.2820, time: 0.09s
Epoch 128, train loss:   8.5107, test loss:   0.2821, time: 0.09s
Epoch 129, train loss:   8.5104, test loss:   0.2821, time: 0.09s
Epoch 130, train loss:   8.5101, test loss:   0.2821, time: 0.09s
Epoch 131, train loss:   8.5097, test loss:   0.2820, time: 0.08s
Epoch 132, train loss:   8.5094, test loss:   0.2821, time: 0.09s
Epoch 133, train loss:   8.5091, test loss:   0.2821, time: 0.09s
Epoch 134, train loss:   8.5088, test loss:   0.2821, time: 0.09s
Epoch 135, train loss:   8.5084, test loss:   0.2822, time: 0.09s
Epoch 136, train loss:   8.5081, test loss:   0.2822, time: 0.09s
Epoch 137, train loss:   8.5077, test loss:   0.2822, time: 0.09s
Epoch 138, train loss:   8.5074, test loss:   0.2822, time: 0.09s
Epoch 139, train loss:   8.5071, test loss:   0.2822, time: 0.09s
Epoch 140, train loss:   8.5068, test loss:   0.2821, time: 0.09s
Epoch 141, train loss:   8.5064, test loss:   0.2820, time: 0.09s
Epoch 142, train loss:   8.5061, test loss:   0.2819, time: 0.09s
Epoch 143, train loss:   8.5058, test loss:   0.2819, time: 0.09s
Epoch 144, train loss:   8.5054, test loss:   0.2819, time: 0.09s
Epoch 145, train loss:   8.5051, test loss:   0.2819, time: 0.09s
Epoch 146, train loss:   8.5048, test loss:   0.2819, time: 0.08s
Epoch 147, train loss:   8.5044, test loss:   0.2820, time: 0.09s
Epoch 148, train loss:   8.5041, test loss:   0.2820, time: 0.09s
Epoch 149, train loss:   8.5038, test loss:   0.2821, time: 0.09s
Epoch 150, train loss:   8.5034, test loss:   0.2822, time: 0.09s
Epoch 151, train loss:   8.5031, test loss:   0.2822, time: 0.09s
Epoch 152, train loss:   8.5028, test loss:   0.2823, time: 0.09s
Epoch 153, train loss:   8.5024, test loss:   0.2823, time: 0.09s
Epoch 154, train loss:   8.5021, test loss:   0.2824, time: 0.09s
Epoch 155, train loss:   8.5017, test loss:   0.2825, time: 0.09s
Epoch 156, train loss:   8.5014, test loss:   0.2825, time: 0.09s
Epoch 157, train loss:   8.5011, test loss:   0.2826, time: 0.09s
Epoch 158, train loss:   8.5007, test loss:   0.2826, time: 0.09s
Epoch 159, train loss:   8.5004, test loss:   0.2827, time: 0.09s
Epoch 160, train loss:   8.5000, test loss:   0.2826, time: 0.09s
Epoch 161, train loss:   8.4997, test loss:   0.2829, time: 0.09s
Epoch 162, train loss:   8.4994, test loss:   0.2826, time: 0.09s
Epoch 163, train loss:   8.4992, test loss:   0.2833, time: 0.09s
Epoch 164, train loss:   8.4991, test loss:   0.2824, time: 0.09s
Epoch 165, train loss:   8.4992, test loss:   0.2837, time: 0.08s
Epoch 166, train loss:   8.4997, test loss:   0.2822, time: 0.09s
Epoch 167, train loss:   8.4990, test loss:   0.2833, time: 0.09s
Epoch 168, train loss:   8.4978, test loss:   0.2831, time: 0.08s
Epoch 169, train loss:   8.4972, test loss:   0.2824, time: 0.09s
Epoch 170, train loss:   8.4975, test loss:   0.2835, time: 0.09s
Epoch 171, train loss:   8.4976, test loss:   0.2826, time: 0.09s
Epoch 172, train loss:   8.4965, test loss:   0.2828, time: 0.09s
Epoch 173, train loss:   8.4960, test loss:   0.2835, time: 0.09s
Epoch 174, train loss:   8.4964, test loss:   0.2826, time: 0.09s
Epoch 175, train loss:   8.4960, test loss:   0.2832, time: 0.09s
Epoch 176, train loss:   8.4952, test loss:   0.2833, time: 0.09s
Epoch 177, train loss:   8.4950, test loss:   0.2826, time: 0.08s

KeyboardInterrupt: